# main.py – PathShalaAI FastAPI application entry point
#
# Run locally:
#   uvicorn main:app --reload --port 8000
#
# API docs (auto-generated by FastAPI):
#   http://localhost:8000/docs   ← Swagger UI
#   http://localhost:8000/redoc  ← ReDoc

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from database import engine
from models import Base

# Routers
from routers import auth, documents, chat, tests, analytics

# ─── Logging ──────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


# ─── Lifespan (replaces on_event startup/shutdown) ────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Startup: create all SQLite tables from the ORM models.
    Shutdown: nothing to clean up (SQLite + ChromaDB persist to disk automatically).
    """
    logger.info("PathShalaAI starting up…")
    Base.metadata.create_all(bind=engine)
    logger.info("SQLite tables ready.")
    yield
    logger.info("PathShalaAI shutting down.")


# ─── FastAPI app ──────────────────────────────────────────────────

app = FastAPI(
    title="PathShalaAI API",
    description=(
        "Backend for PathShalaAI – upload study materials, chat with an AI tutor, "
        "and auto-generate quizzes using RAG + Gemini."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# ─── CORS ─────────────────────────────────────────────────────────
# Allows the HTML frontend (served from file:// or a local HTTP server)
# to make requests to this FastAPI backend.
# In production, replace "*" with your actual frontend domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],      # ← tighten this in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Register routers ─────────────────────────────────────────────
app.include_router(auth.router)
app.include_router(documents.router)
app.include_router(chat.router)
app.include_router(tests.router)
app.include_router(analytics.router)


# ─── Health check ─────────────────────────────────────────────────
@app.get("/health", tags=["Health"])
def health():
    """Quick liveness probe – returns 200 if the server is running."""
    return {"status": "ok", "service": "PathShalaAI"}